name: Code Analysis

on:
  push

jobs:
  code_analysis:
    name: ${{ matrix.actions.name }} on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0']

        actions:
          -   name: Rector
              run: 'vendor/bin/rector process app --dry-run --debug'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1

      - run: ${{ matrix.actions.run }}
